[package]
name = "keeper"
version = "0.0.0"
description = "The one that deploys host."
keywords = ["deploy", "docker", "self-hosted"]
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
response = { version = "2.0.0", features = ["axum"] }
deploy = { path = "../../../libs/deploy" }
anyhow = "1.0.104"
axum = { version = "0.8.9", features = ["multipart"] }
serde_json = "1.0.151"
tokio = { version = "1.53.2", features = ["rt-multi-thread", "macros", "net", "signal", "sync", "fs"] }
mimalloc = "0.1.52"
serde = { version = "1.0.229", features = ["derive"] }
